### ISSUE TITLE
Access to App Group container fails on macOS

### ISSUE THREAD

**Issue by keeshux** [keeshux/tunnelkit#79]
App Group directory seems to be returned malformed, so log complains about "ca.pem folder not found" on tunnel start.

**Comment by johankool** [comment]
I ran into this issue too. It turned out that for BasicTunnel-macOS and BasicTunnelExtension-macOS the App Groups capability wasn't yet enabled. I set it to `$(TeamIdentifierPrefix)group.com.companyname.projectname` and did the same for the line in ViewController.swift but with expanded version of that string as it appears in the Xcode Capabilities tab. 

I now have a different error. 😄 (TunnelKitErrorCodeCryptoBoxEncryption, but using .ovpn file instead of defaults in the demo app.)

**Comment by keeshux** [comment]
Awesome, I'll take a look. I tend to find the App Group concept a bit misleading on macOS.

On the other hand, what encryption algorithm are you using? An excerpt of the debug log might help, but you should post that in new different issue.

**Comment by keeshux** [comment]
Yeah, it was the team ID. I admit I fail to understand when to use it or not. E.g. iOS works both with and without. Not to mention the shared keychain. It makes no sense to me, whatever!

**Comment by johankool** [comment]
Cool! Still verifying some stuff on my side regarding the encryption error first before raising issue here. Hopefully you never hear about that from me. :-)

**Comment by keeshux** [comment]
Do not hesitate to create a new issue and close it yourself in case you find a solution, it could be helpful as a reference. Thank you again and have a nice day!
